name: "Test"
on:
  pull_request:
  release:
jobs:
  test:
    strategy:
      matrix:
        template:
          - ""
          - haskell-nix
          - plutus
        system:
          - "aarch64-linux"
          - "x86_64-linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: klarkc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: ./.github/workflows/test.sh ${{ system }} ${{ matrix.template }}
