name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        template:
          - ""
          - hask
          - iogx
          - hix-plutus
          - pix
          - pix-ctl
          - pix-ctl-full
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - template: iogx
            os: macos-latest
          - template: hix-plutus
            os: macos-latest
          - template: pix
            os: macos-latest
          - template: pix-ctl
            os: macos-latest
          - template: pix-ctl-full
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            template:
              - ${{ matrix.template && format('{0}/**', matrix.template) || 'flake.*' }}
              - CHANGELOG.md
              - .github/workflows/test.*
      - if: steps.changes.outputs.template == 'true' 
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - if: steps.changes.outputs.template == 'true' 
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BUILDER_TOKEN }}
      - if: ${{ steps.changes.outputs.template == 'true' && matrix.os == 'macos-latest' }}
        run: |
          brew install gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH" >> $GITHUB_PATH
      - if: steps.changes.outputs.template == 'true'
        uses: gacts/run-and-post-run@v1
        with:
          run: |
            curl https://raw.githubusercontent.com/cachix/cachix-action/master/dist/main/list-nix-store.sh --output ./.github/workflows/list-nix-store.sh
            chmod +x ./.github/workflows/list-nix-store.sh
            ./.github/workflows/list-nix-store.sh > /tmp/store
            ./.github/workflows/test.sh ${{ matrix.template }}
          post: |
            ./.github/workflows/list-nix-store.sh > /tmp/store-new
            comm -13 <(sort /tmp/store) <(./.github/workflows/list-nix-store.sh) > /tmp/store-new
            mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
            cp .github/workflows/known_hosts ~/.ssh/known_hosts
            (cat /tmp/store-new | nix -v copy -s --stdin --to ssh://builder@cache.tcp4.me) || EXIT_CODE=$?
            echo $EXIT_CODE
