name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        template:
          - ""
          - hask
          - hix
          - hix-plutus
          - hor
          - hor-plutus
          - pix
          - pix-ctl
          - pix-ctl-full
        system:
          - x86_64-linux
          - x86_64-darwin
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - system: x86_64-linux
            os: macos-latest
          - system: x86_64-darwin
            os: ubuntu-latest
          - template: hor
            system: x86_64-darwin
          - template: hor-plutus
            system: x86_64-darwin
          - template: pix
            system: x86_64-darwin
          - template: pix-ctl
            system: x86_64-darwin
          - template: pix-ctl-full
            system: x86_64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            template:
              - ${{ matrix.template && format('{0}/**', matrix.template) || 'flake.*' }}
              - CHANGELOG.md
              - .github/workflows/test.*
      - if: steps.changes.outputs.template == 'true' 
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - if: steps.changes.outputs.template == 'true' 
        uses: cachix/cachix-action@v12
        with:
          name: klarkc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - if: ${{ steps.changes.outputs.template == 'true' && matrix.os == 'macos-latest' }}
        run: |
          brew install gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH" >> $GITHUB_PATH
      - if: steps.changes.outputs.template == 'true' 
        run: ./.github/workflows/test.sh ${{ matrix.system }} ${{ matrix.template }}
