name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        target:
          - name: ""
            free: false
            os: ubuntu-latest
          # FIXME macos-latest tests disabled in CI
          #- name: ""
          #  free: false
          #  os: macos-latest
          # FIXME hask and agd flakes not running mac CI tests
          #   error: flake 'git+file:///private/tmp/nix-templates/target' does not provide attribute 'devShells.aarch64-darwin.default', 'devShell.aarch64-darwin', 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'
          - name: agd
            free: false
            os: ubuntu-latest
          - name: hask
            free: false
            os: ubuntu-latest
          - name: iogx
            free: false
            os: ubuntu-latest
          - name: iogx-plutus
            free: false
            os: ubuntu-latest
          - name: pix
            free: false
            os: ubuntu-latest
          - name: pix-ctl
            free: false
            os: ubuntu-latest
          - name: pix-ctl-full
            free: true
            os: ubuntu-latest
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            template:
              - ${{ matrix.target.name && format('{0}/**', matrix.target.name) || 'flake.*' }}
              - CHANGELOG.md
              - .github/workflows/test.*
      - if: steps.changes.outputs.template == 'true' 
        uses: DeterminateSystems/determinate-nix-action@v3.8.2
      - if: steps.changes.outputs.template == 'true' 
        uses: DeterminateSystems/magic-nix-cache-action@v13
      - if: steps.changes.outputs.template == 'true' 
        uses: DeterminateSystems/flake-checker-action@v12
        with:
          flake-lock-path: ./${{ matrix.target.name }}/flake.lock
          fail-mode: true
          # TODO enable check-outdated check on flake-checker-action 
          check-outdated: false
      - if: ${{ steps.changes.outputs.template == 'true' && matrix.target.os == 'macos-latest' }}
        run: |
          brew install gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH" >> $GITHUB_PATH
      - if: ${{ steps.changes.outputs.template == 'true' && matrix.target.os == 'ubuntu-latest' && matrix.target.free }}
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
