name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        template:
          - ""
          - hix
          - hix-plutus
        system:
          - aarch64-linux
          - x86_64-linux
        include:
          - template: hor
            system: x86_64-linux
          - template: hor-plutus
            system: x86_64-linux
          - template: pix
            system: x86_64-linux
          - template: pix-ctl
            system: x86_64-linux
          - template: pix-ctl-full
            system: x86_64-linux
          - template: pix-purenix
            system: x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            template:
              - ${{ matrix.template && format('{0}/**', matrix.template) || 'flake.*' }}
              - CHANGELOG.md
      - if: steps.changes.outputs.template == 'true' 
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - if: steps.changes.outputs.template == 'true' 
        uses: cachix/cachix-action@v12
        with:
          name: klarkc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - if: steps.changes.outputs.template == 'true' 
        run: ./.github/workflows/test.sh ${{ matrix.system }} ${{ matrix.template }}
