name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        template:
          - ""
          - hask
          - hix
          - hix-plutus
          - pix
          - pix-ctl
          - pix-ctl-full
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - template: hix
            os: macos-latest
          - template: hix-plutus
            os: macos-latest
          - template: pix
            os: macos-latest
          - template: pix-ctl
            os: macos-latest
          - template: pix-ctl-full
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            template:
              - ${{ matrix.template && format('{0}/**', matrix.template) || 'flake.*' }}
              - CHANGELOG.md
              - .github/workflows/test.*
      - if: steps.changes.outputs.template == 'true' 
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - if: steps.changes.outputs.template == 'true' 
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BUILDER_TOKEN }}
      - if: ${{ steps.changes.outputs.template == 'true' && matrix.os == 'macos-latest' }}
        run: |
          brew install gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH" >> $GITHUB_PATH
      - if: steps.changes.outputs.template == 'true'
        uses: gacts/run-and-post-run@v1
        with:
          run: ./.github/workflows/test.sh ${{ matrix.template }}
          post: |
            mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
            cp .github/workflows/known_hosts ~/.ssh/known_hosts
            nix -v copy -s --all --to ssh://builder@cache.tcp4.me
