name: update-flake-lock-inputs
on:
  workflow_dispatch: # allows manual triggering
    inputs:
      templates: 
        description: 'Template paths (sep by spaces)'
        required: true
      input:
        description: 'Flake inputs to update (sep by spaces)'
        required: true
jobs:
  lockfile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [${{ github.event.inputs.templates }}]
        input: [${{ github.event.inputs.flake_inputs }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update ${{ matrix.template }} flake.lock ${{ matrix.input }}
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          path-to-flake-dir: ${{ matrix.template }}
          commit-msg: "build(${{ matrix.template }}): Bump flake.lock ${{ matrix.input }}"
          pr-title: "Update ${{ matrix.template }} flake.lock ${{ matrix.input }}" 
          pr-labels: |                  
            dependencies
            automated
          token: ${{ secrets.PAT_TOKEN }}
          branch: "update_${{ matrix.template }}_flake_lock_${{ matrix.input }}_action"
      - name: Send notification on failure
        if: ${{ failure() }}
        uses: actions-cool/issues-helper@v3
        with:
          actions: create-issue
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update of ${{ matrix.template }} ${{ matrix.input }} failure
          body: The [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) workflow failed. Check the workflow run for details.
          labels: automated
